/* Ocorrencias BH
   Migracao 002 - dados iniciais
   Compatibilidade: Firebird 3.0

   Pode ser executada novamente: os registros existentes serao atualizados
   pelas chaves informadas em MATCHING.
*/

UPDATE OR INSERT INTO LOJAS
    (CODIGO, NOME, CIDADE, ENDERECO, REGIONAL, GERENTE, TELEFONE, EMAIL,
     HORARIO_FUNCIONAMENTO, STATUS)
VALUES
    ('036', 'Loja 036', 'Betim', 'Av. Edmeia Mattos Lazzarotti, 420',
     'Oeste', 'Fernanda Alves', '(31) 3333-0036',
     'loja036@ocorrenciasbh.local', '08:00 às 21:00', 'ATIVA')
MATCHING (CODIGO);

UPDATE OR INSERT INTO LOJAS
    (CODIGO, NOME, CIDADE, ENDERECO, REGIONAL, GERENTE, TELEFONE, EMAIL,
     HORARIO_FUNCIONAMENTO, STATUS)
VALUES
    ('087', 'Loja 087', 'Belo Horizonte', 'Av. Amazonas, 2850',
     'Belo Horizonte', 'Carla Souza', '(31) 3333-0087',
     'loja087@ocorrenciasbh.local', '07:00 às 23:00', 'ATIVA')
MATCHING (CODIGO);

UPDATE OR INSERT INTO LOJAS
    (CODIGO, NOME, CIDADE, ENDERECO, REGIONAL, GERENTE, TELEFONE, EMAIL,
     HORARIO_FUNCIONAMENTO, STATUS)
VALUES
    ('142', 'Loja 142', 'Contagem', 'Av. João César de Oliveira, 1200',
     'Metropolitana', 'Marcos Silva', '(31) 3333-0142',
     'loja142@ocorrenciasbh.local', '07:00 às 22:00', 'ATIVA')
MATCHING (CODIGO);

UPDATE OR INSERT INTO LOJAS
    (CODIGO, NOME, CIDADE, ENDERECO, REGIONAL, GERENTE, TELEFONE, EMAIL,
     HORARIO_FUNCIONAMENTO, STATUS)
VALUES
    ('215', 'Loja 215', 'Santa Luzia', 'Av. Brasília, 650',
     'Norte', 'Renato Lima', '(31) 3333-0215',
     'loja215@ocorrenciasbh.local', '07:00 às 22:00', 'ATIVA')
MATCHING (CODIGO);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Produtos e Estoque', 'Perdas', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Recebimento de Mercadorias', 'Recebimento', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Segurança e Fiscalização', 'Segurança', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Manutenção', 'Manutenção', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Frente de Caixa', 'Caixa', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Recursos Humanos', 'RH', TRUE)
MATCHING (NOME);

UPDATE OR INSERT INTO CATEGORIAS (NOME, TIPO, ATIVA)
VALUES ('Limpeza e Organização', 'Limpeza', TRUE)
MATCHING (NOME);

/* Produtos e Estoque */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto vencido encontrado na gôndola', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto próximo do vencimento', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto avariado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Embalagem danificada', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto contaminado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto sem etiqueta', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto com preço divergente', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Falta de produto na gôndola', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Ruptura de estoque', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto armazenado incorretamente', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto fora da temperatura adequada', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Descarte de mercadoria', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Quebra de mercadoria', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Vazamento de produto', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Produtos e Estoque'), 'Produto furtado', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Recebimento de Mercadorias */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Divergência de nota fiscal', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Falta de mercadoria na entrega', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Excesso de mercadoria na entrega', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Produto recebido vencido', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Produto recebido avariado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Temperatura inadequada no recebimento', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Lacre violado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Veículo de entrega inadequado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recebimento de Mercadorias'), 'Fornecedor fora do padrão', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Segurança e Fiscalização */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Suspeita de furto', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Furto confirmado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Consumo de produto sem pagamento', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Troca de etiquetas', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Violação de embalagem', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Tentativa de fraude', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Acesso não autorizado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Comportamento suspeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Acidente com cliente', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Segurança e Fiscalização'), 'Acidente com colaborador', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Manutenção */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Equipamento quebrado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Câmara fria com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Geladeira com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Vazamento de água', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Vazamento de gás', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Problema elétrico', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Iluminação defeituosa', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Ar-condicionado com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Carrinho danificado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Esteira de caixa com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Impressora com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Manutenção'), 'Balança com defeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Frente de Caixa */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Divergência de caixa', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Cancelamento suspeito', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Falha de sistema', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Falha de impressora fiscal', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Falha em leitor de código de barras', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Produto sem cadastro', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Troco incorreto', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Reclamação de cliente', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Frente de Caixa'), 'Fila excessiva', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Recursos Humanos */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Falta injustificada', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Atraso', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Descumprimento de procedimento', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Não utilização de EPI', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Conflito entre colaboradores', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Mau atendimento', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Recursos Humanos'), 'Treinamento pendente', TRUE)
MATCHING (CATEGORIA_ID, NOME);

/* Limpeza e Organização */
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Área suja', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Piso molhado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Risco de acidente', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Lixeira cheia', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Praga identificada', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Produto fora do local correto', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Depósito desorganizado', TRUE)
MATCHING (CATEGORIA_ID, NOME);
UPDATE OR INSERT INTO TIPOS_OCORRENCIA (CATEGORIA_ID, NOME, ATIVO)
VALUES ((SELECT ID FROM CATEGORIAS WHERE NOME = 'Limpeza e Organização'), 'Falha no 5S', TRUE)
MATCHING (CATEGORIA_ID, NOME);

COMMIT;
